In [2]:
import torch

In [30]:
torch.manual_seed(1111)
example = torch.rand(2,5)
print(f"\nRaw example: \n{example}")

layer = torch.nn.Sequential(torch.nn.Linear(5,6), torch.nn.ReLU())
output = layer(example)
print(f"\nOutput: \n{output}")

print(f"\nOutput Mean:\n{output.mean(dim=-1)}")
print(f"\nOutput Variance:\n{output.var(dim=-1)}")



Raw example: 
tensor([[0.4606, 0.0850, 0.8009, 0.3972, 0.9548],
        [0.5982, 0.4821, 0.9446, 0.5145, 0.8125]])

Output: 
tensor([[0.3231, 0.0000, 0.0000, 0.3538, 0.0000, 0.0000],
        [0.5535, 0.0000, 0.0000, 0.4951, 0.0000, 0.0000]],
       grad_fn=<ReluBackward0>)

Output Mean:
tensor([0.1128, 0.1748], grad_fn=<MeanBackward1>)

Output Variance:
tensor([0.0306, 0.0736], grad_fn=<VarBackward0>)


In [31]:
layer_norm = torch.nn.LayerNorm(6)
output_ln = layer_norm(output)

print(f"\nLayer Norm Output Mean:\n{output_ln.mean(dim=-1)}")
print(f"\nLayer Norm Output Variance:\n{output_ln.var(dim=-1)}")



Layer Norm Output Mean:
tensor([-3.9736e-08,  0.0000e+00], grad_fn=<MeanBackward1>)

Layer Norm Output Variance:
tensor([1.1995, 1.1998], grad_fn=<VarBackward0>)
